-- MySQL Script generated by MySQL Workbench
-- Fri May  3 08:17:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema umbrella
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema umbrella
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `umbrella` DEFAULT CHARACTER SET utf8 ;
USE `umbrella` ;

-- -----------------------------------------------------
-- Table `umbrella`.`pacients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `umbrella`.`pacients` (
  `idpacients` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `age` VARCHAR(45) NULL,
  `adress` VARCHAR(45) NULL,
  PRIMARY KEY (`idpacients`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `umbrella`.`hospitals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `umbrella`.`hospitals` (
  `idhospitals` INT NOT NULL,
  `harmonia` VARCHAR(45) NULL,
  `genesis` VARCHAR(45) NULL,
  `avicena` VARCHAR(45) NULL,
  `gemotest` VARCHAR(45) NULL,
  PRIMARY KEY (`idhospitals`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `umbrella`.`doctors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `umbrella`.`doctors` (
  `iddoctors` INT NOT NULL,
  `dname` VARCHAR(45) NULL,
  `dsurname` VARCHAR(45) NULL,
  `hospitals_idhospitals` INT NOT NULL,
  `post` VARCHAR(45) NULL,
  `doctorscol` VARCHAR(45) NULL,
  `key` TINYINT NULL,
  PRIMARY KEY (`iddoctors`),
  INDEX `fk_doctors_hospitals1_idx` (`hospitals_idhospitals` ASC) VISIBLE,
  CONSTRAINT `fk_doctors_hospitals1`
    FOREIGN KEY (`hospitals_idhospitals`)
    REFERENCES `umbrella`.`hospitals` (`idhospitals`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `umbrella`.`graphics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `umbrella`.`graphics` (
  `idgraphics` INT NOT NULL,
  `doctors_iddoctors` INT NOT NULL,
  `hoidays_begin` DATE NULL,
  `holidays_end` DATE NULL,
  `workingdays` VARCHAR(45) NULL,
  PRIMARY KEY (`idgraphics`),
  INDEX `fk_graphics_doctors1_idx` (`doctors_iddoctors` ASC) VISIBLE,
  CONSTRAINT `fk_graphics_doctors1`
    FOREIGN KEY (`doctors_iddoctors`)
    REFERENCES `umbrella`.`doctors` (`iddoctors`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `umbrella`.`documents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `umbrella`.`documents` (
  `iddocuments` INT NOT NULL,
  `SNILS` INT NOT NULL,
  `insurance` INT NOT NULL,
  `pasport` INT NOT NULL,
  `pacients_idpacients` INT NOT NULL,
  `referral` VARCHAR(45) NULL,
  PRIMARY KEY (`iddocuments`),
  INDEX `fk_documents_pacients1_idx` (`pacients_idpacients` ASC) VISIBLE,
  CONSTRAINT `fk_documents_pacients1`
    FOREIGN KEY (`pacients_idpacients`)
    REFERENCES `umbrella`.`pacients` (`idpacients`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `umbrella`.`health_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `umbrella`.`health_card` (
  `idhealth_card` INT NOT NULL,
  `pacients_idpacients` INT NOT NULL,
  `hospitals_idhospitals` INT NOT NULL,
  `consent` VARCHAR(500) NULL,
  `accounting_date` DATE NULL,
  `diagnoses` VARCHAR(45) NULL,
  `sick_leave` VARCHAR(500) NULL,
  `checks` DATE NULL,
  `expertise_plan` VARCHAR(500) NULL,
  `medecine` VARCHAR(500) NULL,
  PRIMARY KEY (`idhealth_card`),
  INDEX `fk_health_card_pacients1_idx` (`pacients_idpacients` ASC) VISIBLE,
  INDEX `fk_health_card_hospitals1_idx` (`hospitals_idhospitals` ASC) VISIBLE,
  CONSTRAINT `fk_health_card_pacients1`
    FOREIGN KEY (`pacients_idpacients`)
    REFERENCES `umbrella`.`pacients` (`idpacients`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_health_card_hospitals1`
    FOREIGN KEY (`hospitals_idhospitals`)
    REFERENCES `umbrella`.`hospitals` (`idhospitals`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `umbrella`.`reg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `umbrella`.`reg` (
  `idreg` INT NOT NULL,
  `regname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `ypost` VARCHAR(45) NULL,
  `postkey` TINYINT NULL,
  `password` VARCHAR(45) NULL,
  `pacients_idpacients` INT NOT NULL,
  `doctors_iddoctors` INT NOT NULL,
  PRIMARY KEY (`idreg`),
  INDEX `fk_reg_pacients1_idx` (`pacients_idpacients` ASC) VISIBLE,
  INDEX `fk_reg_doctors1_idx` (`doctors_iddoctors` ASC) VISIBLE,
  CONSTRAINT `fk_reg_pacients1`
    FOREIGN KEY (`pacients_idpacients`)
    REFERENCES `umbrella`.`pacients` (`idpacients`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reg_doctors1`
    FOREIGN KEY (`doctors_iddoctors`)
    REFERENCES `umbrella`.`doctors` (`iddoctors`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
