# Generated by Django 4.2.16 on 2024-12-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('regname', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role_code', models.IntegerField(blank=True, null=True)),
                ('building_code', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('patient', 'Patient')], max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='reguser_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='reguser_permissions_set', to='auth.permission')),
            ],
            options={
                'db_table': 'reg',
            },
        ),
    ]
